version: '3.3'
services:
    app:
        image: docker-node-express-mongoapp
        restart: always
        build: .
        ports:
            - '80:3700'
        links:
            - mongo
    mongo: 
        container_name: mongo
        image: mongo
        ports:
            - '27017:27017'
